name: calendhub-blog-astro
services:
- name: web
  source_dir: /
  github:
    repo: CalendHub-Org/CalendHub-Blog-Astro
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: HOST
    value: "0.0.0.0"
  - key: ADMIN_EMAIL
    value: kgabeci@gmail.com
    type: SECRET
  - key: ADMIN_PASS  
    value: Unjamadi97?!
    type: SECRET